apiVersion: v1
kind: Pod
metadata:
  name: meupod01
  labels:
    app: web
    versao: blue
spec:
  containers:
  - name: web
    image: kubedevio/web-color:blue
    ports:
    - name: http
      containerPort: 80
      protocol: TCP

---

apiVersion: v1
kind: Pod
metadata:
  name: meupod02
  labels:
    app: web
    versao: green
spec:
  containers:
  - name: web
    image: kubedevio/web-color:green
    ports:
    - name: http
      containerPort: 80
      protocol: TCP